---
extends:
  - ./packages/commitlint-config-peakfijn
rules:
  scope-empty: [0, never]
  scope-enum:
    - 2
    - always
    -
      - changelog
      - commit-types
      - commitizen
      - commitlint
      - config-commitizen
      - config-commitlint
      - config-release-expo
      - config-release-laravel
      - config-release-react
      - release-rules
