---
extends:
  - ./packages/commitlint-config-peakfijn
rules:
  scope-empty: [0, never]
  scope-enum:
    - 2
    - always
    -
      - commitizen
      - commitlint
      - eslint
      - semantic-release
      - stylelint
